name: Main

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  conda-size:
    name: Conda size
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.conda-size.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nix-setup
      - id: conda-size
        run: |
          nix run --print-build-logs .#pytorch-conda-size \
            | jq -cr '"json=\(.)"' \
            | tee -a "$GITHUB_OUTPUT"

  docker-image-size:
    name: Docker image size
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.docker-image-size.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nix-setup
      - id: docker-image-size
        run: |
          nix run --print-build-logs .#pytorch-docker-image-size \
            | jq -cr '"json=\(.)"' \
            | tee -a "$GITHUB_OUTPUT"

  nix-store-size:
    name: Nix store size
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.nix-store-size.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nix-setup
      - id: nix-store-size
        run: |
          nix run --print-build-logs .#pytorch-nix-store-size \
            | jq -cr '"json=\(.)"' \
            | tee -a "$GITHUB_OUTPUT"

  nix-binary-cache-size-xz:
    name: Nix binary cache size (xz)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # compression-level: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        compression-level: [1, 2]
    outputs:
      xz_1_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_1_json }}
      xz_2_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_2_json }}
      # xz_3_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_3_json }}
      # xz_4_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_4_json }}
      # xz_5_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_5_json }}
      # xz_6_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_6_json }}
      # xz_7_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_7_json }}
      # xz_8_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_8_json }}
      # xz_9_json: ${{ steps.nix-binary-cache-size-xz.outputs.xz_9_json }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nix-setup
      - id: nix-binary-cache-size-xz
        run: |
          nix run --print-build-logs .#pytorch-nix-binary-cache-size-xz-${{ matrix.compression-level }} \
            | jq -cr '"xz_${{ matrix.compression-level }}_json=\(.)"' \
            | tee -a "$GITHUB_OUTPUT"

  nix-binary-cache-size-zstd:
    name: Nix binary cache size (zstd)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # compression-level: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        compression-level: [1, 2, 3, 4]
    outputs:
      zstd_1_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_1_json }}
      zstd_2_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_2_json }}
      zstd_3_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_3_json }}
      zstd_4_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_4_json }}
      # zstd_5_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_5_json }}
      # zstd_6_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_6_json }}
      # zstd_7_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_7_json }}
      # zstd_8_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_8_json }}
      # zstd_9_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_9_json }}
      # zstd_10_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_10_json }}
      # zstd_11_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_11_json }}
      # zstd_12_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_12_json }}
      # zstd_13_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_13_json }}
      # zstd_14_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_14_json }}
      # zstd_15_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_15_json }}
      # zstd_16_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_16_json }}
      # zstd_17_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_17_json }}
      # zstd_18_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_18_json }}
      # zstd_19_json: ${{ steps.nix-binary-cache-size-zstd.outputs.zstd_19_json }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nix-setup
      - id: nix-binary-cache-size-zstd
        run: |
          nix run --print-build-logs .#pytorch-nix-binary-cache-size-zstd-${{ matrix.compression-level }} \
            | jq -cr '"zstd_${{ matrix.compression-level }}_json=\(.)"' \
            | tee -a "$GITHUB_OUTPUT"

  markdown-summary:
    name: Markdown summary
    runs-on: ubuntu-latest
    needs:
      - conda-size
      - docker-image-size
      - nix-store-size
      - nix-binary-cache-size-xz
      - nix-binary-cache-size-zstd
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nix-setup
      - name: Conda size markdown
        env:
          JSON: ${{ needs.conda-size.outputs.json }}
        run: |
          nix develop --command -- \
              python3 ./.github/scripts/markdown_formatter \
              --app Conda \
              <<< "$JSON" \
            | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Docker image size markdown
        env:
          JSON: ${{ needs.docker-image-size.outputs.json }}
        run: |
          nix develop --command -- \
              python3 ./.github/scripts/markdown_formatter \
              --app DockerImage \
              <<< "$JSON" \
            | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Nix store size markdown
        env:
          JSON: ${{ needs.nix-store-size.outputs.json }}
        run: |
          nix develop --command -- \
              python3 ./.github/scripts/markdown_formatter \
              --app NixStore \
              <<< "$JSON" \
            | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Nix binary cache size (xz) markdown
        env:
          JSON1: ${{ needs.nix-binary-cache-size-xz.outputs.xz_1_json }}
          JSON2: ${{ needs.nix-binary-cache-size-xz.outputs.xz_2_json }}
        run: |
          JSON="[$JSON1,$JSON2]"
          nix develop --command -- \
              python3 ./.github/scripts/markdown_formatter \
              --app NixBinaryCache \
              --batched \
              --include-time \
              <<< "$JSON" \
            | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Nix binary cache size (zstd) markdown
        env:
          JSON1: ${{ needs.nix-binary-cache-size-zstd.outputs.zstd_1_json }}
          JSON2: ${{ needs.nix-binary-cache-size-zstd.outputs.zstd_2_json }}
          JSON3: ${{ needs.nix-binary-cache-size-zstd.outputs.zstd_3_json }}
          JSON4: ${{ needs.nix-binary-cache-size-zstd.outputs.zstd_4_json }}
        run: |
          JSON="[$JSON1,$JSON2,$JSON3,$JSON4]"
          nix develop --command -- \
              python3 ./.github/scripts/markdown_formatter \
              --app NixBinaryCache \
              --batched \
              --include-time \
              <<< "$JSON" \
            | tee -a "$GITHUB_STEP_SUMMARY"
